# Generated by Django 4.1.4 on 2022-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_3',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
