# Generated by Django 4.1.4 on 2022-12-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_3',
            field=models.CharField(max_length=255),
        ),
    ]
